server:
  port: 8081
  use-forward-headers: true
  tomcat:
    remote_ip_header: x-forwarded-for
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jst?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: jst
    password: jsT*1234
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    max-idle: 5
    min-idle: 0
mybatis:
  mapper-locations: classpath:com/jst/model/map/*.xml
  type-aliases-package: com.hjf.boot.demo.boot_mybatis.domain
logging:
  #配置日志文件路径
  path: ./logs
  level:
    org.springfromework.web: info
    com.jst.web: error
  config: classpath:logback-spring.xml