DROP TABLE IF EXISTS jst_member;
CREATE TABLE jst_member(
  id BIGINT AUTO_INCREMENT PRIMARY KEY ,
  phone VARCHAR(11) NOT NULL ,
  name VARCHAR(30) NOT NULL ,
  password VARCHAR(100) DEFAULT '123456',
  register_time DATETIME DEFAULT now(),
  update_time DATETIME DEFAULT now()
) ENGINE=Innodb CHARSET=UTF8 COMMENT '会员管理表';

SELECT * FROM jst_member;